version: '3.4'

services:
  wmbackend:
    image: wmbackend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    network_mode: "host"
    command: npx nodemon --legacy-watch start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
